name: Update gist with WakaTime stats
on:
  push:
    branches: main
  schedule:
    - cron: "24 17 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 006c77d11113b6d2dfaec549e15c8cc0
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
